# system-wide environment settings for zsh if on macOS
if [[ "$OSTYPE" == darwin* && -x /usr/libexec/path_helper ]]; then
  eval `/usr/libexec/path_helper -s`
fi

# Ignore global rcfiles.
setopt no_global_rcs

# Load machine-local zshenv if exists.
if [[ -s "${ZDOTDIR:-$HOME}/.zshenv.local" ]]; then
  source "${ZDOTDIR:-$HOME}/.zshenv.local"
fi
