# Load original
source "${ZDOTDIR:-$HOME}/.zprezto/runcoms/zshrc"

# Colors
autoload -Uz colors
colors

case $OSTYPE in
  darwin*)
    export CLICOLOR=1
    if (type gls >/dev/null 2>&1); then
      alias ls="${aliases[ls]:-ls} -F --color=auto --time-style=long-iso"
    else
      alias ls="${aliases[ls]:-ls} -G -F -T"
    fi
    ;;
  linux*|msys*)
    alias ls="${aliases[ls]:-ls} -F --color=auto --time-style=long-iso"
    ;;
esac

export LSCOLORS=gxfxcxdxbxegedabagacag
export LS_COLORS='di=36;40:ln=35;40:so=32;40:pi=33;40:ex=31;40:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;46'
zstyle ':completion:*' list-colors 'di=34' 'ln=35' 'so=32' 'ex=31' 'bd=46;34' 'cd=43;34'

# History
export HISTCONTROL=ignoreboth
HISTFILE=${ZDOTDIR:-$HOME}/.zsh_history
HISTSIZE=500000
SAVEHIST=500000
setopt hist_ignore_dups
setopt hist_ignore_all_dups
setopt hist_ignore_space
setopt hist_save_nodups
setopt hist_find_no_dups
setopt hist_reduce_blanks
setopt hist_no_store
setopt share_history

# PATH
path=(
    $HOME/.local/bin(N-/)
    $HOME/bin(N-/)
    $path
)

# Homebrew
path=(
    /home/linuxbrew/.linuxbrew/bin(N-/)
    $HOME/.linuxbrew/bin(N-/)
    $path
)

if type brew &>/dev/null
then
  eval $(brew shellenv)
  export BREW_PREFIX="$(brew --prefix)"
  FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
fi

# Completion
setopt auto_menu

fpath=(
  /usr/local/share/zsh-completions(N-/)
  /usr/local/share/zsh/site-functions(N-/)
  /usr/share/zsh/site-functions(N-/)
  /usr/share/zsh/vendor-completions(N-/)
  ${ZDOTDIR:-$HOME}/.zsh/completion(N-/)
  $fpath
)

if ( type brew &>/dev/null ) then
  FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
fi

autoload -Uz compinit
compinit -u

zstyle ':completion:*' ignore-parents parent pwd ..
zstyle ':completion:*:sudo:*' command-path \
  /usr/local/sbin \
  /usr/local/bin \
  /usr/sbin \
  /usr/bin \
  /sbin \
  /bin \
  /usr/X11R6/bin

# Misc options
setopt print_eight_bit
setopt no_beep
setopt no_flow_control
setopt interactive_comments
setopt auto_pushd
setopt pushd_ignore_dups
setopt rm_star_silent

# Fix annoying settings
setopt no_extended_glob
setopt clobber
setopt no_auto_cd
setopt no_correct
setopt no_correct_all

# Key bindings
bindkey '^S' history-incremental-search-forward
bindkey '^R' history-incremental-search-backward

#
# Aliases and Functions
#
function gi() { curl -sL https://www.toptal.com/developers/gitignore/api/$@ ;}
alias awsec2ls="aws ec2 describe-instances --filter \"Name=instance-state-name,Values=running\" --query 'Reservations[].Instances[].{Name: (Tags[?Key==\`Name\`].Value|[0]), InstanceId: InstanceId}'"

# Load machine-local zshrc if exists.
if [[ -s "${ZDOTDIR:-$HOME}/.zshrc.local" ]]; then
  source "${ZDOTDIR:-$HOME}/.zshrc.local"
fi

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
