# Load original
source "${ZDOTDIR:-$HOME}/.zprezto/runcoms/zshrc"

export LSCOLORS='gxfxcxdxbxegedabagacag'
export LS_COLORS='di=36;40:ln=35;40:so=32;40:pi=33;40:ex=31;40:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;46'
zstyle ':completion:*' list-colors 'di=34' 'ln=35' 'so=32' 'ex=31' 'bd=46;34' 'cd=43;34'

# History
export HISTCONTROL="ignoreboth"
HISTFILE="${ZDOTDIR:-$HOME}/.zsh_history"
HISTSIZE=500000
SAVEHIST=500000
setopt hist_ignore_dups
setopt hist_ignore_all_dups
setopt hist_ignore_space
setopt hist_save_nodups
setopt hist_find_no_dups
setopt hist_reduce_blanks
setopt hist_no_store
setopt share_history

# PATH
path=(
  $HOME/.local/bin(N-/)
  $HOME/bin(N-/)
  $HOMEBREW_PREFIX/opt/gnu-getopt/bin(N-/)
  $HOMEBREW_PREFIX/opt/gnu-sed/libexec/gnubin(N-/)
  $HOMEBREW_PREFIX/opt/gnu-tar/libexec/gnubin(N-/)
  $path
)

# Homebrew
if ( type brew &>/dev/null ); then
  eval "$(brew shellenv)"
  fpath=(
    $HOMEBREW_PREFIX/share/zsh/site-functions(N-/)
    $fpath
  )
fi

# asdf-vm
if ( type asdf &>/dev/null ); then
  fpath=(
    ${ASDF_DATA_DIR:-$HOME/.asdf}/completions(N-/)
    $fpath
  )
fi

# Completion
setopt auto_menu

fpath=(
  /usr/local/share/zsh-completions(N-/)
  /usr/local/share/zsh/site-functions(N-/)
  /usr/share/zsh/site-functions(N-/)
  /usr/share/zsh/vendor-completions(N-/)
  ${ZDOTDIR:-$HOME}/.zsh/completions(N-/)
  $fpath
)

zstyle ':completion:*' ignore-parents parent pwd ..
zstyle ':completion:*:sudo:*' command-path \
  /usr/local/sbin \
  /usr/local/bin \
  /usr/sbin \
  /usr/bin \
  /sbin \
  /bin \
  /usr/X11R6/bin

# Colors
autoload -Uz colors
colors

case $OSTYPE in
  darwin*)
    export CLICOLOR=1
    if (type gls >/dev/null 2>&1); then
      alias ls="${aliases[ls]:-ls} -F --color=auto --time-style=long-iso"
    else
      alias ls="${aliases[ls]:-ls} -G -F -T"
    fi
    ;;
  linux*|msys*)
    alias ls="${aliases[ls]:-ls} -F --color=auto --time-style=long-iso"
    ;;
esac

# Misc options
setopt print_eight_bit
setopt no_beep
setopt no_flow_control
setopt interactive_comments
setopt auto_pushd
setopt pushd_ignore_dups
setopt rm_star_silent

# Fix annoying settings
setopt no_extended_glob
setopt clobber
setopt no_auto_cd
setopt no_correct
setopt no_correct_all

# Key bindings
bindkey '^S' history-incremental-search-forward
bindkey '^R' history-incremental-search-backward

#
# Aliases and Functions
#
function gi() { curl -sL https://www.toptal.com/developers/gitignore/api/$@ ;}
alias awsec2ls="aws ec2 describe-instances --filter \"Name=instance-state-name,Values=running\" --query 'Reservations[].Instances[].{Name: (Tags[?Key==\`Name\`].Value|[0]), InstanceId: InstanceId}'"
alias gpf='git push --force-if-includes'

# Load local path settings
if [[ -s "${ZDOTDIR:-$HOME}/.zshrc.path" ]]; then
  source "${ZDOTDIR:-$HOME}/.zshrc.path"
fi

# Load local environment variables and aliases
if [[ -s "${ZDOTDIR:-$HOME}/.zshrc.local" ]]; then
  source "${ZDOTDIR:-$HOME}/.zshrc.local"
fi

# Initialize completion system if cache is not available or outdated
autoload -Uz compinit

local zcd_file="${ZDOTDIR:-$HOME}/.zcompdump"

if [[ ! -f "$zcd_file" || -n "$zcd_file"(#qN.m+1) ]]; then
  # Regenerate .zcompdump if it's more than a day old.
  compinit
else
  # Otherwise, initialize with the cache for faster startup.
  compinit -C
fi

# Load local settings that should be run after compinit (tool initializations)
if [[ -s "${ZDOTDIR:-$HOME}/.zshrc.post" ]]; then
  source "${ZDOTDIR:-$HOME}/.zshrc.post"
fi
