# Path
typeset -gU cdpath fpath mailpath path
path=(
  /usr/local/{bin,sbin}
  $path
)

# History
export HISTCONTROL=ignoreboth
HISTFILE=${ZDOTDIR:-$HOME}/.zsh_history
HISTSIZE=500000
SAVEHIST=500000
setopt hist_ignore_dups
setopt hist_ignore_all_dups
setopt hist_ignore_space
setopt hist_save_nodups
setopt hist_find_no_dups
setopt hist_reduce_blanks
setopt hist_no_store
setopt share_history

# Completion
setopt auto_menu

fpath=(
  /usr/local/share/zsh-completions(N-/)
  /usr/local/share/zsh/site-functions(N-/)
  /usr/share/zsh/site-functions(N-/)
  ${ZDOTDIR:-$HOME}/.zsh/completion(N-/)
  $fpath
)
autoload -Uz compinit
compinit -u

zstyle ':completion:*' ignore-parents parent pwd ..
zstyle ':completion:*:sudo:*' command-path \
  /usr/local/sbin \
  /usr/local/bin \
  /usr/sbin \
  /usr/bin \
  /sbin \
  /bin \
  /usr/X11R6/bin

# Misc options
setopt print_eight_bit
setopt no_beep
setopt no_flow_control
setopt interactive_comments
setopt auto_pushd
setopt pushd_ignore_dups
setopt rm_star_silent
setopt no_extended_glob

# Load machine-local zshrc if exists.
if [[ -s "${ZDOTDIR:-$HOME}/.zshrc.local" ]]; then
  source "${ZDOTDIR:-$HOME}/.zshrc.local"
fi
